CREATE DATABASE echofest;

USE echofest;

CREATE DATABASE echofest;

USE echofest;

CREATE TABLE users (
  id INT  AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  phone VARCHAR(30) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE artists (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  genre VARCHAR(80) NOT NULL,
  bio TEXT DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
);




