CREATE DATABASE IF NOT EXISTS echofest CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE echofest;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  age INT NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lineup (
  id INT AUTO_INCREMENT PRIMARY KEY,
  artist VARCHAR(120) NOT NULL,
  stage VARCHAR(80) NOT NULL,
  day VARCHAR(30) NOT NULL,
  image VARCHAR(255) NOT NULL,
  hits TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tickets (
  id VARCHAR(50) PRIMARY KEY,
  img_class VARCHAR(80) DEFAULT NULL,
  img_src VARCHAR(255) NOT NULL,
  name VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  price INT NOT NULL,
  available TINYINT(1) NOT NULL DEFAULT 0,
  coming_date VARCHAR(100) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  ticket_type VARCHAR(50) DEFAULT NULL,
  ticket_name VARCHAR(120) NOT NULL,
  qty INT NOT NULL,
  event_name VARCHAR(120) NOT NULL,
  event_dates VARCHAR(120) NOT NULL,
  location_code VARCHAR(20) DEFAULT NULL,
  total DECIMAL(10,2) NOT NULL,
  order_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(80) PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  event_date VARCHAR(80) NOT NULL,
  event_time VARCHAR(80) NOT NULL,
  location VARCHAR(120) NOT NULL,
  stage VARCHAR(80) NOT NULL,
  description TEXT NOT NULL,
  artist VARCHAR(120) NOT NULL,
  image VARCHAR(255) NOT NULL,
  category VARCHAR(80) NOT NULL
);
